Repository operator-framework/olm-book, pull requests merged in 2019-10, with the labels that each got.

#2 Add OCP 4.2 new global catalog namespace section
  docs/openshift/important-changes-by-release.md
  index.md
Labels: lgtm, size/L

#3 Document how to package an operator for OLM
  .travis.yml
  docs/packaging-an-operator.md
  index.md
Labels: lgtm, size/L

#4 Add troubleshooting section
  index.md
Labels: lgtm, size/XS

#8 Create operator-dependencies-and-requirements.md
  docs/operator-dependencies-and-requirements.md
  index.md
Labels: lgtm, size/M

#10 Document how to scope an operator
  docs/operator-scoping.md
  index.md
Labels: lgtm, size/L

#6 Add documentation on how to uninstall an Operator
  docs/uninstall-an-operator.md
  index.md
Labels: lgtm, size/M

#9 [docs] install-olm
  docs/install-olm.md
  index.md
Labels: size/M

#5 Add documentation on how to list available operators
  docs/list-available-operators.md
  index.md
Labels: lgtm, size/S

#7 Documentation for "How do I install my operator"
  docs/how-do-i-install-my-operator-with-olm.md
  index.md
Labels: size/M
