Repository operator-framework/olm-book, pull requests merged in 2019-11, with the labels that each got.

#11 [index] fix pushed conflict
  index.md
Labels: lgtm, size/XS

#14 Fix missing install operator link
  index.md
Labels: lgtm, size/XS

#12 add docs for discovering operators (OLM-1326)
  .gitignore
  docs/discover-operator-presence.md
  index.md
Labels: lgtm, size/M

#20 [docs] correcting links
  index.md
Labels: lgtm, size/M

#17 Add OpenShift FAQ on developing default operators
  docs/openshift/faq.md
  docs/openshift/operator-marketplace.md
  index.md
Labels: lgtm, size/M

#18 Documentation for debugging a failing operator install
  docs/troubleshooting.md
  index.md
Labels: size/L
