Repository operator-framework/olm-book, pull requests merged in 2020-01, with the labels that each got.

#25 Add when to update operator doc
  docs/when-to-update-my-operator.md
  index.md
Labels: size/S

#24 Remove redundant troubleshooting link
  index.md
Labels: size/XS

#19 [doc] uninstall olm
  docs/uninstall-olm.md
  index.md
Labels: size/M

#22 force install of marker
  .travis.yml
Labels: size/XS

#27 adding glossary
  docs/glossary.md
  index.md
Labels: lgtm, size/M

#28 Fix snapshot doc link
  index.md
Labels: lgtm, size/XS

#29 Add doc on multiarch labels
  docs/glossary.md
  docs/multiarch.md
  docs/packaging-an-operator.md
  docs/troubleshooting.md
  index.md
Labels: lgtm, size/M

#16 feat: add subscriptions page
  docs/subscriptions.md
  index.md
Labels: size/M

#15 Add validate package documentation
  docs/validate-package.md
  index.md
Labels: lgtm, size/M
